### PR TITLE
update plugin for Kibana 5+

### PR DESCRIPTION
**Pull request by npotier**

### CODE REVIEW

**Comment by npotier** [comment]
Hi, we have updated the plugin in order to make it work with ELK 5.1.1

Feel free to merge if interested :)

**Comment by billmetangmo** [comment]
Hi @npotier ,

I updated my local branch with your modifications and i am now able to add this plugin to my Kibana 5. Thanks :).

But when I tried to use it , i can't because the field can't be set as you can see here:
capture

Did you have the same error ? I used ELK 5.1.1

**Comment by npotier** [comment]
Hi @billmetangmo Thank you for your message, I'm happy to know that my work can be useful.

I had the same trouble as you and i fixed it but I'm not sure I did it the best way.

if you look at the file ``public/sliderController.js``, in the function ``getIndexedNumberFields``,  :
 
```
    $scope.getIndexedNumberFields = function() {
      var fields = $scope.vis.indexPattern.fields.raw;
      var fieldTypes = ["number"];

      if (fieldTypes) {
        fields = $filter('fieldType')(fields, fieldTypes);
        fields = $filter('filter')(fields, { bucketable: true });
        fields = $filter('orderBy')(fields, ['type', 'name']);
      }

      return new IndexedArray({
        index: ['name'],
        initialSet: fields
      });
    };
```

the fieldTypes ``if`` condition was problematic for me. I solved it by commentic the statemment : 
```
    $scope.getIndexedNumberFields = function() {
      var fields = $scope.vis.indexPattern.fields.raw;
      /*
      var fieldTypes = ["number"];

      if (fieldTypes) {
        fields = $filter('fieldType')(fields, fieldTypes);
        fields = $filter('filter')(fields, { bucketable: true });
        fields = $filter('orderBy')(fields, ['type', 'name']);
      }
      */
      return new IndexedArray({
        index: ['name'],
        initialSet: fields
      });
    };
```

Now you should see the fields in Kibana. feel free to adapt this function to satisfy your needs :)

**Comment by billmetangmo** [comment]
Thanks @npotier ! It works fine now  :) .

**Comment by nreese** [comment]
@npotier No need to comment out the entire block. The problem is with the filter on bucketable
`fields = $filter('filter')(fields, { bucketable: true });`

Between Kibana 5 and 4, `src/ui/public/index_patterns/_field.js` was modified and the property bucketable was removed. The line in question filters out all fields and thus the select is not displayed because the array is empty.

**Comment by raystorm-place** [comment]
Thanks!

**Pull request merged**
